# .travis.yml
language:
  golang # 指明使用的语言
go:          # 语言版本号
  - "1.13"   # 默认使用最新版本,注意，需要 "1.10" 版本的时候必须表示为字符串形式，如果写成 1.10 则会使用 1.1 版本;x表示对应前缀的最新版本
script:
  - go mod tidy
  - go build
  - ./HelpPackage