// Code generated by protoc-gen-bm v0.1, DO NOT EDIT.
// source: server.proto

package help_package_v1

import (
	"context"

	bm "github.com/go-kratos/kratos/pkg/net/http/blademaster"
	"github.com/go-kratos/kratos/pkg/net/http/blademaster/binding"
)

// to suppressed 'imported but not used warning'
var _ *bm.Context
var _ context.Context
var _ binding.StructValidator

var PathCcPackageGetNameByCode = "/help_package.v1.CcPackage/GetNameByCode"

// CcPackageBMServer is the server API for CcPackage service.
type CcPackageBMServer interface {
	// rpc funcName (request) returns (response) {}
	GetNameByCode(ctx context.Context, req *GetNameByCodeRequest) (resp *GetNameByCodeResponse, err error)
}

var CcPackageSvc CcPackageBMServer

func ccPackageGetNameByCode(c *bm.Context) {
	p := new(GetNameByCodeRequest)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := CcPackageSvc.GetNameByCode(c, p)
	c.JSON(resp, err)
}

// RegisterCcPackageBMServer Register the blademaster route
func RegisterCcPackageBMServer(e *bm.Engine, server CcPackageBMServer) {
	CcPackageSvc = server
	e.GET("/help_package.v1.CcPackage/GetNameByCode", ccPackageGetNameByCode)
}
